# Generated by Django 4.2.17 on 2025-01-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual_fund_family', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_code', models.CharField(max_length=50, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('net_asset_value', models.FloatField()),
                ('scheme_type', models.CharField(max_length=100)),
                ('scheme_category', models.CharField(max_length=100)),
                ('isin_growth', models.CharField(max_length=50)),
                ('isin_reinvestment', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('mutual_fund_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.mutualfundfamily')),
            ],
        ),
    ]
